### ISSUE TITLE
The page "xyz" cannot be found

### ISSUE THREAD

**Issue by foxacid** [kirby-tools/kirby-content-translator#5]
Sometimes, when translating from secondary to primary language, a page not found error is triggered. 

This is somewhat erratic and hard to reproduce. The page is not actually deleted but the GET request fails. 

I have a hunch that it only occurs for pages that have been created before I activated `importFrom: all` as I cannot reproduce it with freshly created pages. A cache issue?

![Screenshot 2024-10-07 at 09 56 53](https://github.com/user-attachments/assets/0c068b5f-505b-4cbb-91f9-c2fafdfd17f3)

**Comment by foxacid** [comment]
Ok, it was definitely a cache issue (might be related to a regression in Kirby 4.4.0 that was fixed in the latest v4).

**Comment by foxacid** [comment]
Reopening this as it still happens and is definitely maybe probably not related to caching but to title/slug translation. Translating from secondary to primary language with `title` translation active will change the directory name. Here's a video:

https://github.com/user-attachments/assets/f3ef167b-f21a-4161-9137-39bf60c06847

**Comment by johannschopplich** [comment]
Good catch! In this case, the slug translation should simply be skipped to omit this error. Thanks a lot for reporting. Will be fixed in the upcoming version.
