### ISSUE TITLE
Bulk translation button

### ISSUE THREAD

**Issue by foxacid** [kirby-tools/kirby-content-translator#6]
The new bulk translation button is very nice but even with `bulk: true` it only makes sense to display it when more than one secondary language has been set.

**Comment by johannschopplich** [comment]
Thanks for the idea. I agree with you. However, I want to encourage the developer to decide when to allow/disallow this feature and keep the visibility of the button consistent. 

Will keep the issue open for now, in case I change my mind. Maybe a new plugin option would be a good choice?

**Comment by johannschopplich** [comment]
Closing this issue, since the new [Panel view button](https://kirby.tools/docs/content-translator/configuration#panel-view-button) could be used as a section replacement and circumvents this behavior. 🎉
