### ISSUE TITLE
Target language specification

### ISSUE THREAD

**Issue by tideg** [kirby-tools/kirby-content-translator#8]
Is there a way to specify the target language? For example, we would like to use British English instead of American English, which is used by default. If this is not yet possible, this would be a desirable option extension.

**Comment by johannschopplich** [comment]
Hi there! Excellent question.

By default, the target language for DeepL is set by the Panel's current language code ([set in your `languages/en.php`](https://getkirby.com/docs/guide/languages#adding-languages)). In most cases, this will be `en`, you're right.

If you want to dynamically specify British English, you can do so by customizing the function used to translate text. Change your `translateFn` plugin option like this:

```php
return [
    'johannschopplich.content-translator' => [
        'translateFn' => function ($text, $toLanguageCode, $fromLanguageCode) {
            // Map `en` language code to `en-gb`, so that DeepL is specified to translate to British English
            if ($targetLanguage === 'en') {
                $targetLanguage = 'en-gb';
            }

            $deepL = new DeepL();
            return $deepL->translate($text, $targetLanguage, $sourceLanguage);
        }
    ]
];
```

I will update the docs later to cover this use case, it should be common, I guess.

Does this answer your question?

**Comment by tideg** [comment]
Thank you for the suggestion @johannschopplich. Do I need to import any other script into my `config.php`? `$targetLanguage` and `$sourceLanguage` as well as the `DeepL`-Class are unknown.

**Comment by johannschopplich** [comment]
Yes, there was a missing import and the variables were named incorrectly. I've updated the code snippet, but I guess you tried the code based on the (then outdated) email.

Please use this code instead:

```php
use JohannSchopplich\ContentTranslator\DeepL;

return [
    'johannschopplich.content-translator' => [
        'translateFn' => function ($text, $toLanguageCode, $fromLanguageCode = null) {
            if ($toLanguageCode === 'en') {
                $toLanguageCode = 'en-gb';
            }

            $deepL = new DeepL();
            return $deepL->translate($text, $toLanguageCode, $fromLanguageCode);
        }
    ]
];

```

**Comment by tideg** [comment]
Right, I had actually overlooked your update, sorry. Thank you very much, it works perfectly now!

**Comment by johannschopplich** [comment]
Glad to hear that!

**Comment by makkus183** [comment]
Thx @tideg for bringing this up and thx for bringing up a solution @johannschopplich !  https://github.com/kirby-tools/kirby-content-translator/issues/8#issuecomment-2556513025 exactly solved this for me too!

Just an additional question for a feature request: 

Would it be possible to generally send the `locale` ==> `LC_ALL` value from the language file to DeepL if it exists instead of the two-digit langcode?

Like here from my 

```
<?php

return [
    'code' => 'en',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'en_UK'
    ],
    'name' => 'English',
...
```

**Comment by johannschopplich** [comment]
@makkus183 Great idea. Can you please open a separate issue for this feature request? Thanks!

**Comment by makkus183** [comment]
> [@makkus183](https://github.com/makkus183) Great idea. Can you please open a separate issue for this feature request? Thanks!

@johannschopplich sure: https://github.com/kirby-tools/kirby-content-translator/issues/15
